version: '3'

services:
  web:
    build: ./
    volumes:
      - ./app:/app
    #ports:
      #- "80:80"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
      - VIRTUAL_HOST= "your Flask Website URL"
      - LETSENCRYPT_HOST= "your Flask Website URL"
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL= "your noip registered email"
    command: flask run --host=0.0.0.0 --port=80
    #expose:
      #- 8080
networks:
   default:
     external:
       name: proxy
volumes:
  data-volume:

